version: '3.5'
services:
  web_dev:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/todoDev
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:3.6.3
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    name: web_dev
