version: '3.5'
services:
  web:
    image: santebande/pharmacy-search:0.0.1
    command: python -u app.py
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/todoDev
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.3
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=./data/logs
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    name: web
